### ISSUE TITLE
麻烦支持一下hyperf2.1

### ISSUE THREAD

**Issue by cxjhk** [wojiushidashen/hyperf-sms#1]
麻烦支持一下hyperf2.1

**Comment by wojiushidashen** [comment]
可以，升级完通知你


| |
18435134258
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月25日 09:42，从小就很酷 写道：

Closed #1.

**Comment by wojiushidashen** [comment]
https://packagist.org/packages/hyperf-lib/sms#v2.0.1
已经升级成hyperf2.1版本，可以start了


| |
18435134258
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月25日 09:42，18435134258 写道：
可以，升级完通知你


| |
18435134258
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年04月25日 09:42，从小就很酷 写道：

Closed #1.
